# Generated by Django 4.1.3 on 2022-12-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clasificacion', models.CharField(max_length=30)),
                ('producto', models.CharField(max_length=30)),
                ('calorias', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('image', models.CharField(max_length=150)),
            ],
        ),
    ]
